### ISSUE TITLE
CleanSam NullPointerException due to a single unmapped mate pair

### ISSUE THREAD

**Issue by chrarnold** [broadinstitute/picard#1324]
### Instructions

For a BAM file, 1 read pair causes the error below, the other 45 million reads before worked fine. Seems to be an edge case for an undefined read pair property for which one read is marked as unmapped according to the sam flag but has a high MAPQ value nevertheless, whereas the other mate is mapped just fine.

----

### Affected tool(s)
CleanSam

### Affected version(s)
all versions up to Version: 2.20.0-SNAPSHOT

### Description 
```
INFO	2019-05-03 15:10:09	CleanSam	Processed    45,000,000 records.  Elapsed time: 00:07:12s.  Time for last 1,000,000:   10s.  Last read position: chrX:82,195,113
Ignoring SAM validation error: ERROR: Record 45684994, Read name NB551451:36:HMN5MBGX7:3:21505:15711:15179, Mate Alignment start should be 0 because reference name = *.
Ignoring SAM validation error: ERROR: Record 45684994, Read name NB551451:36:HMN5MBGX7:3:21505:15711:15179, Mapped mate should have mate reference name
Ignoring SAM validation error: ERROR: Record 45684994, Read name NB551451:36:HMN5MBGX7:3:21505:15711:15179, MAPQ should be 0 for unmapped read.
Ignoring SAM validation error: ERROR: Record 45684994, Read name NB551451:36:HMN5MBGX7:3:21505:15711:15179, The unaligned mate start position is 0, should be 0
[Fri May 03 15:10:16 CEST 2019] picard.sam.CleanSam done. Elapsed time: 7.35 minutes.
Runtime.totalMemory()=207618048
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.NullPointerException
	at picard.sam.AbstractAlignmentMerger.createNewCigarIfMapsOffEndOfReference(AbstractAlignmentMerger.java:850)
	at picard.sam.AbstractAlignmentMerger.createNewCigarsIfMapsOffEndOfReference(AbstractAlignmentMerger.java:887)
	at picard.sam.CleanSam.doWork(CleanSam.java:92)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
(base) 
```

#### Steps to reproduce
The following read pair causes the issue:
```
NB551451:36:HMN5MBGX7:3:21505:15711:15179	163	chr17	9	42	59M	=	5	59	TTCTCACCCTGTTCCTGCATAGATAATTGCATGACAATTGCCTTGTCCCTGCTGAATGT	AAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEEEE	MC:Z:59M	MD:Z:59	PG:Z:MarkDuplicates	RG:Z:nan.nan	XG:i:0	NM:i:0	XM:i:0	XN:i:0	XO:i:0	MQ:i:42	AS:i:0	YS:i:0	YT:Z:CP
NB551451:36:HMN5MBGX7:3:21505:15711:15179	87	*	0	42	59M	*	5	-59	TTCTCACCCTGTTCCTGCATAGATAATTGCATGACAATTGCCTTGTCCCTGCTGAATGT	EAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAAAAA	MC:Z:59M	MD:Z:59	PG:Z:MarkDuplicates	RG:Z:nan.nan	XG:i:0	NM:i:0	XM:i:0	XN:i:0	XO:i:0	MQ:i:42	AS:i:0	YS:i:0	YT:Z:CP
```

This SAM file reproducibly causes the error:
```

@HD	VN:1.5	SO:coordinate
@SQ	SN:chr1	LN:249250621	M5:1b22b98cdeb4a9304cb5d48026a85128	UR:file:BLA/GATK_bundle/ucsc.hg19.onlyRefChr.fasta
@SQ	SN:chr2	LN:243199373	M5:a0d9851da00400dec1098a9255ac712e	UR:file:BLA/GATK_bundle/ucsc.hg19.onlyRefChr.fasta
@SQ	SN:chr3	LN:198022430	M5:641e4338fa8d52a5b781bd2a2c08d3c3	UR:file:BLA/GATK_bundle/ucsc.hg19.onlyRefChr.fasta
@SQ	SN:chr4	LN:191154276	M5:23dccd106897542ad87d2765d28a19a1	UR:file:BLA/GATK_bundle/ucsc.hg19.onlyRefChr.fasta
@SQ	SN:chr5	LN:180915260	M5:0740173db9ffd264d728f32784845cd7	UR:file:BLA/GATK_bundle/ucsc.hg19.onlyRefChr.fasta
@SQ	SN:chr6	LN:171115067	M5:1d3a93a248d92a729ee764823acbbc6b	UR:file:BLA/GATK_bundle/ucsc.hg19.onlyRefChr.fasta
@SQ	SN:chr7	LN:159138663	M5:618366e953d6aaad97dbe4777c29375e	UR:file:BLA/GATK_bundle/ucsc.hg19.onlyRefChr.fasta
@SQ	SN:chr8	LN:146364022	M5:96f514a9929e410c6651697bded59aec	UR:file:BLA/GATK_bundle/ucsc.hg19.onlyRefChr.fasta
@SQ	SN:chr9	LN:141213431	M5:3e273117f15e0a400f01055d9f393768	UR:file:BLA/GATK_bundle/ucsc.hg19.onlyRefChr.fasta
@SQ	SN:chr10	LN:135534747	M5:988c28e000e84c26d552359af1ea2e1d	UR:file:BLA/GATK_bundle/ucsc.hg19.onlyRefChr.fasta
@SQ	SN:chr11	LN:135006516	M5:98c59049a2df285c76ffb1c6db8f8b96	UR:file:BLA/GATK_bundle/ucsc.hg19.onlyRefChr.fasta
@SQ	SN:chr12	LN:133851895	M5:51851ac0e1a115847ad36449b0015864	UR:file:BLA/GATK_bundle/ucsc.hg19.onlyRefChr.fasta
@SQ	SN:chr13	LN:115169878	M5:283f8d7892baa81b510a015719ca7b0b	UR:file:BLA/GATK_bundle/ucsc.hg19.onlyRefChr.fasta
@SQ	SN:chr14	LN:107349540	M5:98f3cae32b2a2e9524bc19813927542e	UR:file:BLA/GATK_bundle/ucsc.hg19.onlyRefChr.fasta
@SQ	SN:chr15	LN:102531392	M5:e5645a794a8238215b2cd77acb95a078	UR:file:BLA/GATK_bundle/ucsc.hg19.onlyRefChr.fasta
@SQ	SN:chr16	LN:90354753	M5:fc9b1a7b42b97a864f56b348b06095e6	UR:file:BLA/GATK_bundle/ucsc.hg19.onlyRefChr.fasta
@SQ	SN:chr17	LN:81195210	M5:351f64d4f4f9ddd45b35336ad97aa6de	UR:file:BLA/GATK_bundle/ucsc.hg19.onlyRefChr.fasta
@SQ	SN:chr18	LN:78077248	M5:b15d4b2d29dde9d3e4f93d1d0f2cbc9c	UR:file:BLA/GATK_bundle/ucsc.hg19.onlyRefChr.fasta
@SQ	SN:chr19	LN:59128983	M5:1aacd71f30db8e561810913e0b72636d	UR:file:BLA/GATK_bundle/ucsc.hg19.onlyRefChr.fasta
@SQ	SN:chr20	LN:63025520	M5:0dec9660ec1efaaf33281c0d5ea2560f	UR:file:BLA/GATK_bundle/ucsc.hg19.onlyRefChr.fasta
@SQ	SN:chr21	LN:48129895	M5:2979a6085bfe28e3ad6f552f361ed74d	UR:file:BLA/GATK_bundle/ucsc.hg19.onlyRefChr.fasta
@SQ	SN:chr22	LN:51304566	M5:a718acaa6135fdca8357d5bfe94211dd	UR:file:BLA/GATK_bundle/ucsc.hg19.onlyRefChr.fasta
@SQ	SN:chrX	LN:155270560	M5:7e0e2e580297b7764e31dbc80c2540dd	UR:file:BLA/GATK_bundle/ucsc.hg19.onlyRefChr.fasta
@SQ	SN:chrY	LN:59373566	M5:1e86411d73e6f00a10590f976be01623	UR:file:BLA/GATK_bundle/ucsc.hg19.onlyRefChr.fasta
@SQ	SN:chrM	LN:16571	M5:d2ed829b8a1628d16cbeee88e88e39eb	UR:file:BLA/GATK_bundle/ucsc.hg19.onlyRefChr.fasta
@RG	ID:nan.nan	LB:nan	PL:Illumina	SM:A4	PU:nan.nan.A4ii
@PG	ID:bowtie2	PN:bowtie2	VN:2.3.4.3	CL:"/opt/conda/bin/bowtie2-align-s --wrapper basic-0 -p 8 -X 2000 --very-sensitive -t -x BLA/referenceGenome/Bowtie2/hg19 -1 BLA/2.Trimming/A4ii_1.trimmed.fq.gz -2 BLA/2.Trimming/A4ii_2.trimmed.fq.gz"
@PG	ID:MarkDuplicates	VN:2.9.0-1-gf5b9f50-SNAPSHOT	CL:picard.sam.markduplicates.MarkDuplicates INPUT=[BLA/5.Postalignment/3.Filter_chrM/A4ii.cleaned4.BQrecal.rmChrM.s.bam] OUTPUT=BLA/5.Postalignment/4.MarkAndRemove_Duplicates/A4ii.cleaned4.BQrecal.rmChrM.markedDup.s.bam METRICS_FILE=BLA/LOGS_AND_BENCHMARKS/markDuplicates_Picardtools.A4ii_metrics.log REMOVE_DUPLICATES=false ASSUME_SORTED=true VALIDATION_STRINGENCY=SILENT CREATE_INDEX=true    MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP=50000 MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=8000 SORTING_COLLECTION_SIZE_RATIO=0.25 REMOVE_SEQUENCING_DUPLICATES=false TAGGING_POLICY=DontTag DUPLICATE_SCORING_STRATEGY=SUM_OF_BASE_QUALITIES PROGRAM_RECORD_ID=MarkDuplicates PROGRAM_GROUP_NAME=MarkDuplicates READ_NAME_REGEX=<optimized capture of last three ':' separated fields as numeric values> OPTICAL_DUPLICATE_PIXEL_DISTANCE=100 VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json	PN:MarkDuplicates
NB551451:36:HMN5MBGX7:3:21505:15711:15179	163	chr17	9	42	59M	=	5	59	TTCTCACCCTGTTCCTGCATAGATAATTGCATGACAATTGCCTTGTCCCTGCTGAATGT	AAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEEEE	MC:Z:59M	MD:Z:59	PG:Z:MarkDuplicates	RG:Z:nan.nan	XG:i:0	NM:i:0	XM:i:0	XN:i:0	XO:i:0	MQ:i:42	AS:i:0	YS:i:0	YT:Z:CP
NB551451:36:HMN5MBGX7:3:21505:15711:15179	87	*	0	42	59M	*	5	-59	TTCTCACCCTGTTCCTGCATAGATAATTGCATGACAATTGCCTTGTCCCTGCTGAATGT	EAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAAAAA	MC:Z:59M	MD:Z:59	PG:Z:MarkDuplicates	RG:Z:nan.nan	XG:i:0	NM:i:0	XM:i:0	XN:i:0	XO:i:0	MQ:i:42	AS:i:0	YS:i:0	YT:Z:CP
```

#### Expected behavior
Read should be ignored and the command should issue a warning but end without an error

#### Actual behavior
java.lang.NullPointerException

----

**Comment by yfarjoun** [comment]
Sorry for the long delay in response.

Actually the problem is that in the second read, the flags claim that the mate is mapped (87) but the mate has * for RNEXT. If you run FixMateInformation prior to running CleanSam it should work out, I think. 

I agree that a stack-trace isn't the best way to deal with this. I'll look to see if I can emit a better Error message, but it will not complete without an error since the input is in an inconsistent state.

**Comment by chrarnold** [comment]
Hi, thanks for the reply! For me (or us ehre), it is sometimes hard to come up with the right order of tools to ensure that a BAM files is fixed in case of small errors like that. It would be good if errors like that can be caught with an error message like "Error bla. Please run FixMateInformation to fix it" or something to point the user to how to fix the issue. I do not remember whether I tried FixMateInformation for this file, but I vaguely remember that it also did not work. Would it be possible to skip read pairs with errors and a corresponding warning message so that the tools at least runs through?

Thanks!

**Comment by yfarjoun** [comment]
hmmm. skipping these reads would mean creating an invalid output bam, which we are somewhat opposed to doing. if running FixMateInfo doesn't solve this, please reopen this ticket with a new example bam that has correct mate information and is valid, but still breaks CleanSam. 

Also please remember that CleanSam is doing a very simple thing: "Cleans the provided SAM/BAM, soft-clipping beyond-end-of-reference alignments and setting MAPQ to 0 for unmapped reads."

**Comment by chrarnold** [comment]
Hi, thanks for the reply! Why is the file invalid if the read pair is skipped, this is not clear to me? I don't recall the files but if I find it I let you know.
You are right, the description is clear and also "easy", but the tool addresses and fixes some of the issues that can happen in a BAM file, but not all, and indirectly requires mate pair information to be correct, so it depends on certain things that are not really mentioned in the tool description in a way, right? I think this can be highlighted more clearly. If FixMateInformation struggles with and crashes for some of the issues that CleanSam repairs, then there is a circular dependency that hopefully never happens. Thanks for the answer, I just wanted to give my viewpoint and experience with the tools, as a frequent user :)
