### ISSUE TITLE
test --tests doesn't work properly after barclay update

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/picard#924]
### Affected tool(s)
running tests manually on the command line

### Affected version(s)
- [ x ] Latest public release version [version?]
- [ x ] Latest development/master branch as of [date of test?]

### Description 
Running 
```
./gradlew tests --tests "*<SomeTestClass>*"
```
 or 
```
./gradlew tests -Dtest.single=<SomeTestClass>
```

 should restrict the tests to only run the test class you explicitly asked for.  

Since the barclay introduction it runs all the tests and then the one you asked for.  This seems to be because the new gradle `test` task depends on the `barclayTest` task.  So it first executes that task which runs all the tests and then runs your restricted test set after that.

The workaround is to run  `./gradlew legacyTest --tests "*<SomeTestClass>*"`  which will only run one set of tests.  

I would have expected that the `--tests` and `-Dtest.single` parameters are propagated to all tasks of type test, so I'm not sure why they're not being respected by `barclayTest` when run as a prerequisite for `test`  

Seems like we need to dive into the gradle and figure out what's going on.  In the meantime, use the `barclayTest` and `legacyTest` tasks instead of `test` when invoking on the command line.

**Comment by lbergelson** [comment]
@eitanbanks Here's the ticket for what we were talking about yesterday.

**Comment by kbergin** [comment]
It seems this has been addressed via #984

**Comment by cmnbroad** [comment]
@kbergin I assume you meant to refer to https://github.com/samtools/htsjdk/issues/984, which is an htsjdk issue that has a similar manifestation but a different cause. AFAIK this issue still exists in Picard, although it is a duplicate of https://github.com/broadinstitute/picard/issues/1211. Finally, note that these issues would be eliminated if we moved forward with https://github.com/broadinstitute/picard/issues/1120.
